CREATE DATABASE IF NOT EXISTS resto_mvp;
USE resto_mvp;

CREATE TABLE IF NOT EXISTS menu_items (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(120) NOT NULL,
	description TEXT NULL,
	price DECIMAL(10,2) NOT NULL,
	is_available TINYINT(1) NOT NULL DEFAULT 1,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	INDEX idx_menu_items_is_available (is_available)
);
